---
kind: Service
apiVersion: v1
metadata:
  name: thestandard-prd
spec:
  type: LoadBalancer
  selector:
    app: thestandard-prd
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thestandard-prd
  annotations:
    description: economicforum2021.thestandard.co development
    kubernetes.io/change-cause: Setup thestandard v.1.0 (conf db env. use domain)
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thestandard-prd
  template:
    metadata:
      labels:
        app: thestandard-prd
    spec:
      containers:
        - name: nginx
          image: registry.digitalocean.com/thestandard/thestandard:1.15
          command: ["/root/run.sh"]
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            requests:
              cpu: 500m
              memory: "2000Mi"
---

